/* eslint-disable */
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { a } from '@aws-amplify/data-schema';
import { configure } from '@aws-amplify/data-schema/internals';
import { secret } from '@aws-amplify/backend';

export const schema = configure({
  database: {
    identifier: 'ID7579947023c5a5ddb9784c7211820410',
    engine: 'postgresql',
    connectionUri: secret('SQL_CONNECTION_STRING'),
  },
}).schema({
  registrations: a
    .model({
      id: a.string(),
      name: a.string().required(),
      email: a.string().required(),
      squad: a.string(),
      player_type: a.string().required(),
      batting_style: a.string().required(),
      bowling_style: a.string().required(),
      bowling_arm: a.string().required(),
      cricket_experience: a.string(),
      jersey_size: a.string(),
      availability: a.string().required(),
      created_at: a.datetime().required(),
      photo_url: a.string(),
      employee_id: a.string(),
      gender: a.string().required(),
      location: a.string().required(),
      dpl_played: a.boolean(),
      self_rating: a.integer().required(),
      visitor_id: a.string(),
    })
    .identifier(['id'])
    .authorization((allow) => [allow.guest()]),

  settings: a
    .model({
      id: a.integer(),
      registration_open: a.datetime(),
      registration_deadline: a.datetime(),
      player_capacity: a.integer().required(),
      total_teams: a.integer().required(),
      total_matches: a.integer().required(),
      champion: a.string(),
      updated_at: a.datetime(),
    })
    .identifier(['id'])
    .authorization((allow) => [allow.guest()]),

  teams: a
    .model({
      id: a.string(),
      name: a.string().required(),
      icon: a.string().required(),
      sort_order: a.integer().required(),
      code: a.string(),
      icon_url: a.string().required(),
      theme: a.string().required(),
      owner: a.string(),
      captain: a.string(),
      champion: a.boolean().required(),
    })
    .identifier(['id'])
    .authorization((allow) => [allow.guest()]),

  team_players: a
    .model({
      id: a.string(),
      team_id: a.string().required(),
      player_id: a.string().required(),
      role: a.string().required(),
      created_at: a.datetime().required(),
    })
    .identifier(['id'])
    .authorization((allow) => [allow.guest()]),

  admin_users: a
    .model({
      email: a.string(),
      created_at: a.datetime().required(),
    })
    .identifier(['email'])
    .authorization((allow) => [allow.group('admin')]),

  admin_audit: a
    .model({
      id: a.integer(),
      actor_email: a.string(),
      action: a.string().required(),
      target_id: a.string(),
      detail: a.json(),
      created_at: a.datetime().required(),
    })
    .identifier(['id'])
    .authorization((allow) => [allow.group('admin')]),

  player_edit_requests: a
    .model({
      id: a.string(),
      player_id: a.string().required(),
      player_name: a.string().required(),
      changes: a.json().required(),
      status: a.string().required(),
      admin_note: a.string(),
      created_at: a.datetime().required(),
      reviewed_at: a.datetime(),
      visitor_id: a.string(),
    })
    .identifier(['id'])
    .authorization((allow) => [
      allow.guest().to(['create']),
      allow.group('admin').to(['read', 'update', 'delete']),
    ]),

  page_views: a
    .model({
      id: a.integer(),
      path: a.string().required(),
      session_id: a.string().required(),
      viewed_at: a.datetime().required(),
      device: a.string(),
      browser: a.string(),
      os: a.string(),
      referrer: a.string(),
    })
    .identifier(['id'])
    .authorization((allow) => [allow.group('admin')]),

  sessions: a
    .model({
      id: a.string(),
      started_at: a.datetime().required(),
      last_seen: a.datetime().required(),
      page_count: a.integer().required(),
      device: a.string(),
      browser: a.string(),
      os: a.string(),
      referrer: a.string(),
      is_active: a.boolean().required(),
      ip_hash: a.string(),
      country: a.string(),
      region: a.string(),
      city: a.string(),
      isp: a.string(),
      visitor_id: a.string(),
      visit_number: a.integer(),
      language: a.string(),
      screen: a.string(),
      fingerprint: a.string(),
    })
    .identifier(['id'])
    .authorization((allow) => [allow.group('admin')]),

  ip_geo: a
    .model({
      ip_hash: a.string(),
      country: a.string(),
      region: a.string(),
      city: a.string(),
      isp: a.string(),
      updated_at: a.datetime().required(),
    })
    .identifier(['ip_hash'])
    .authorization((allow) => [allow.group('admin')]),

  auction_sessions: a
    .model({
      id: a.string(),
      name: a.string().required(),
      status: a.string().required(),
      purse_budget: a.integer().required(),
      increment: a.integer().required(),
      started_at: a.datetime(),
      ended_at: a.datetime(),
      created_at: a.datetime().required(),
      updated_at: a.datetime().required(),
      lot_timer_seconds: a.integer().required(),
    })
    .identifier(['id'])
    .authorization((allow) => [allow.group('admin')]),

  auction_results: a
    .model({
      id: a.string(),
      session_id: a.string().required(),
      player_id: a.string().required(),
      lot_order: a.integer().required(),
      base_price: a.integer().required(),
      status: a.string().required(),
      sold_to_team_id: a.string(),
      sold_price: a.integer(),
      created_at: a.datetime().required(),
      updated_at: a.datetime().required(),
      opens_at: a.datetime(),
    })
    .identifier(['id'])
    .authorization((allow) => [allow.group('admin')]),

  auction_bids: a
    .model({
      id: a.string(),
      session_id: a.string().required(),
      player_id: a.string().required(),
      team_id: a.string().required(),
      amount: a.integer().required(),
      created_at: a.datetime().required(),
    })
    .identifier(['id'])
    .authorization((allow) => [allow.group('admin')]),

  auction_purses: a
    .model({
      id: a.string(),
      session_id: a.string().required(),
      team_id: a.string().required(),
      budget: a.integer().required(),
      created_at: a.datetime().required(),
    })
    .identifier(['id'])
    .authorization((allow) => [allow.group('admin')]),
});
